---
- hosts: ansible-server
  gather_facts: no
  roles:
    - dependencies
    - ec2-instance


- name: Configure instance(s)
  hosts: jenkins-server
  become: yes
  gather_facts: no

  roles:
    - bootstrap
    - InstallJenkins
    - SetupJenkins
    - jenkinsJobBuilder
    - post_build
