  - name: Create required directories.
    become: yes
    file:
      group: "{{ jenkins_job_builder_user_group }}"
      owner: "{{ jenkins_job_builder_user_name }}"
      path: "{{ item }}"
      state: directory
    with_items:
      - /etc/jenkins_jobs


  - name: copy jenkins_jobs.ini
    template: >
      src=jenkins_jobs.ini.j2
      dest={{ jenkins_job_builder_template_jenkins_jobs_ini_dest }}
      mode=0700
    become: yes

  - name: Create jobs directory.
    become: yes
    file:
      dest: "{{ jenkins_job_builder_file_jobs_dest }}"
      mode: "{{ jenkins_job_builder_file_jobs_mode }}"
      state: directory

  - name: Give Sudo access to Jenkins
    lineinfile:
      dest: /etc/sudoers
      line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    become: yes

  - name: Rsync checkbox.io jenkins jobs configuration.
    become: yes
    synchronize:
      delete: yes
      dest: "{{ jenkins_job_builder_file_checkboxjobs_dest }}"
      perms: yes
      src: "{{ jenkins_job_builder_file_checkboxjobs_src }}"
    when: jenkins_job_builder_file_checkboxjobs_src != ""
    # notify:
    #   - Reload checkboxjenkins-jobs

  - meta: flush_handlers
