---
- name: Gather ec2 facts for checkbox main server
  ec2_metadata_facts:

- name: Get checkbox MAIN server instance ID
  debug:
    msg: "{{ ansible_ec2_instance_id }}"

- name: create CPU Utilization Alarm for checkbox MAIN SERVER
  ec2_metric_alarm:
    state: present
    region: "us-east-2"
    aws_access_key: "{{ lookup('ini', 'aws_access_keyID section=aws file=./credentials.ini') }}"
    aws_secret_key: "{{ lookup('ini', 'aws_secret_key section=aws file=./credentials.ini') }}"
    name: "CPUAlert"
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: Average
    comparison: ">="
    threshold: 50.0
    period: 60
    evaluation_periods: 1
    unit: "Percent"
    description: "CPU Utilization of checkbox MAIN server is HIGHER than or EQUAL to 50%"
    dimensions: {'InstanceId':'{{ ansible_ec2_instance_id }}'}
    alarm_actions: ["arn:aws:cloudwatch:us-east-2:*:alarm:CPUAlert"]
