---
- name: Checking the status of the checkbox.io build
  shell: cat /var/lib/jenkins/jobs/checkboxBuildJob/lastSuccessful/log | grep SUCCESS
  register: checkboxlog
  become: yes

- debug:
    var:  checkboxlog.stdout
  when: checkboxlog.stdout != ""



- import_tasks: post_build.yml
  when: checkboxlog.stdout != ""
