---
- hosts: jenkins
  gather_facts: no
  roles:
    - dependencies
    - post-ec2-instance-checkBox


- name: Configure checkBox EC2 instance
  hosts: checkbox
  become: yes
  gather_facts: no
  roles:
    - bootstrap
    - CBDependencies

- name: Configure MongoDB Instance
  hosts: loadBalancer
  become: yes
  gather_facts: no
  roles:
    - bootstrap
    - MongoInstance
    - canaryRelease

- name: Configure checkbox
  hosts: checkbox[0]
  become: yes
  gather_facts: no
  roles:
    - CBSetup
    - Chaos

- name: Configure checkbox
  hosts: checkbox[1]
  become: yes
  gather_facts: no
  roles:
    - CBSetup1
