---
- name: Installing python-pip
  apt:
    name: python-pip
    state: latest
    update_cache: yes
  become: yes

- name: Installing 'boto' and 'boto3' in order to use AWS EC2 Ansible module
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - boto
    - boto3

#  http://docs.ansible.com/ansible/latest/modules/sns_topic_module.html
- name: Create alarm SNS topic for CPU Utilization of checkboxio main server
  sns_topic:
    name: "CPUAlert"
    state: present
    region: "us-east-2"
    aws_access_key: "{{ lookup('ini', 'aws_access_keyID section=aws file=./credentials.ini') }}"
    aws_secret_key: "{{ lookup('ini', 'aws_secret_key section=aws file=./credentials.ini') }}"
    display_name: "High CPU Utilization in checkboxio main server"
    subscriptions:
      - endpoint: "{{ lookup('ini', 'emailID section=email file=./credentials.ini') }}"
        protocol: "email"
