---
- name: Pause for 2 minutes
  pause:
    minutes: 2

- name: Starting nginx service
  service:
    name: nginx
    state: started
  register: nginx_state

- name: Send notification message via Slack
  slack:
    token: "{{ lookup('ini', 'token section=slack file=./credentials.ini') }}"
    msg: "Nginx service is up again!!"
    channel: "#general"
    username: "Checkbox-bot"
  when: nginx_state is changed
