---
  - name: Installing python-pip
    apt:
      name: python-pip
      state: latest
      update_cache: yes
    become: yes

  - name: Installing 'boto' and 'boto3' in order to use AWS EC2 Ansible module
    pip:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - boto
      - boto3


  #https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
  #Adding nodejs PPA
  - name: Installing python packages for nodejs and npm
    apt:
      name: python-software-properties
      state: present
      update_cache: yes
      cache_valid_time: 1800
    become: yes

  - name: Adding nodejs PPA
    shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
    become: yes

  - name: Installing git,npm,nodejs
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      cache_valid_time: 1800
    become: yes
    with_items:
      - git
      - nodejs
