---
- name: Restart Jenkins
  service: name=jenkins state=restarted
  become: yes
  when: jenkins_default|changed or plugin_install|changed

- name: Wait for Jenkins to restart
  uri:
    url: http://127.0.0.1:8080
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: jenkins_default|changed or plugin_install|changed
