- name: add github ssh key
  copy: >
      src=id_rsa
      dest=.ssh/id_rsa
      mode=0600

- name: configure ssh to use ansible key for github.com
  template: >
      src=ssh_config.j2
      dest=.ssh/config
      mode=0644
